<!--
  AGENTS.md.tpl — Template for repo-specific agent instructions
  Template version: 1.1
  Generated by harness-os v{{VERSION}}
  
  This file is processed by `harness init` to create AGENTS.md for new repos.
  Variables: {{REPO_NAME}}, {{VERSION}}, {{DATE}}, {{STACK}}, {{PM_NAME}}, {{PM_INSTALL}}, {{PM_RUN}}
  Conditionals: {{#if_node}}, {{#if_dotnet}}, {{#if_python}}, {{#if_go}}, {{#if_php}}, {{#if_rust}}
-->

# {{REPO_NAME}} — Agent Instructions

> Generated by harness-os v{{VERSION}} on {{DATE}}. Stack: {{STACK}}. Package manager: {{PM_NAME}}.

{{OLD_AGENTS_NOTE}}

---

## Project Overview

This is a **{{STACK}}** project managed by harness-os. The harness ensures agents verify before claiming done, stay within scope, maintain context across sessions, and learn from patterns.

- **Repo:** {{REPO_NAME}}
- **Stack:** {{STACK}}
- **Package Manager:** {{PM_NAME}}
- **Harness version:** {{VERSION}}

---

## Build Commands

{{#if_node}}
```bash
{{PM_INSTALL}}           # Install dependencies
{{PM_RUN}} build         # Build project
{{PM_RUN}} test          # Run tests
{{PM_RUN}} lint          # Lint check
```

> Note: This repo uses **{{PM_NAME}}**. If not available, use npm as fallback.
{{/if_node}}
{{#if_dotnet}}
```bash
dotnet restore              # Install dependencies
dotnet build --no-restore   # Build project
dotnet test --no-build      # Run tests
dotnet format --verify-no-changes  # Lint check
```
{{/if_dotnet}}
{{#if_python}}
```bash
pip install -e .    # Install dependencies
pytest              # Run tests
ruff check .        # Lint check
```
{{/if_python}}
{{#if_go}}
```bash
go mod download     # Install dependencies
go build ./...      # Build project
go test ./...       # Run tests
golangci-lint run   # Lint check
```
{{/if_go}}
{{#if_php}}
```bash
composer install         # Install dependencies
composer dump-autoload   # Regenerate autoloader
vendor/bin/phpunit       # Run tests
vendor/bin/phpcs         # Lint (PSR-12)
```
{{/if_php}}
{{#if_rust}}
```bash
cargo build         # Build project
cargo test          # Run tests
cargo clippy        # Lint check
```
{{/if_rust}}

---

## Test Commands

Run `verify_run(".")` to execute the full verification pipeline (install → build → test → lint). All steps must pass before marking a task as done.

---

## Conventions

- Follow existing code style and patterns in this repo
- Use the project's established naming conventions
- Write tests for new functionality
- Keep changes surgical — touch only what the task requires
- Log progress after each meaningful change

---

## Boundaries

- **Scope enforcement:** Check `scope_check` before editing unexpected files
- **Forbidden paths:** See `.harness/scope.yaml` for restricted areas
- **Feature boundaries:** See `.harness/feature_list.json` for scope per feature
- **Never claim done without verification** — run `verify_run` first

---

## Setup Checklist

Before you can use harness tools, one-time setup is required:

1. **Install CLI** — `npm install -g harness-os` or use the project's local install
2. **Install MCP config** — Run `harness install-mcp --ide cursor` (or your IDE name)
   - This configures your IDE to connect to the harness MCP server
   - Supported IDEs: `cursor`, `vscode`, `claude-code`, `kiro`, `antigravity`, `opencode`
3. **Verify** — Run `harness doctor` to confirm everything works
4. **Initialize** — Run `harness init` (already done if you're reading this file)

---

## Harness-OS MCP Tools

These are the 31 MCP tools available through the harness server. Tools are organized by domain and callable directly by the agent.

### Session Lifecycle

| Action | Tool | Notes |
|--------|------|-------|
| Start new session | `session_start({ repo_path })` | Returns session_id + pending tasks |
| Resume existing session | `session_resume({ repo_path })` | Alias for session_start with continue semantics |
| End without handoff | `session_end({ session_id })` | Use only if no handoff is needed |
| End with full handoff | `session_handoff({ session_id, summary, unfinished, next_steps })` | Always preferred — writes handoff + progress atomically |

### Task Management

| Action | Tool | Notes |
|--------|------|-------|
| Create task | `task_create({ title, scope, session_id })` | scope limits file access for this task |
| Update task status | `task_update({ task_id, status })` | status: pending/in-progress/done/blocked |
| List tasks | `task_list({ repo_path, status })` | Filter by status to find next work item |

### Verification & Quality

| Action | Tool | Notes |
|--------|------|-------|
| Full verification | `verify_run({ repo_path, steps, task_id })` | Runs install → build → test → lint |
| Save evidence | `verify_run` with `task_id` | Evidence auto-saved when task_id is provided |

### Skills & Learning

| Action | Tool | Notes |
|--------|------|-------|
| Load a skill | `skill_load({ name })` | Returns skill markdown content |
| List skills | `skill_list({ stack_filter })` | Filter by stack (node, dotnet, etc.) |
| Suggest skills | `skill_suggest({ task_title, stack })` | Let harness find relevant skills |
| Create skill from session | `skill_create_from_session({ session_id, theme })` | Generate SKILL.md draft from audit log |

### Instincts (Pattern Memory)

| Action | Tool | Notes |
|--------|------|-------|
| Get learned instincts | `instinct_get({ tags, min_confidence })` | Filter by tags to find relevant patterns |
| Add a new instinct | `instinct_add({ description, tags })` | Document a pattern for future sessions |
| Record outcome | `instinct_record_outcomes({ session_id, outcome })` | outcome: success/failure |
| Prune instincts | `instinct_prune({ confidence_below, dry_run })` | Use dry_run first to preview |
| Evolve to skill | `instinct_evolve({ tag_cluster })` | Needs 5+ instincts in a cluster |
| Promote instinct | `instinct_promote({ instinct_id })` | Make pending instinct permanent |

### Scope & Boundaries

| Action | Tool | Notes |
|--------|------|-------|
| Check file scope | `scope_check({ repo_path, file_path, task_id })` | Check before editing any file |
| Get scope config | `scope_get({ repo_path, task_id })` | View allowed/forbidden paths |

### State & Progress

| Action | Tool | Notes |
|--------|------|-------|
| Log progress | `progress_log({ repo_path, entry })` | entry: { summary, status, task_id, files_changed } |
| Read feature list | `feature_list_read({ repo_path })` | View scope per feature |
| Update feature list | `feature_list_update({ repo_path, feature_id, patch })` | Update feature status |
| Read handoff | `handoff_read({ repo_path })` | Get context from previous session |
| Write handoff | `handoff_write({ repo_path, session_id, next_steps, unfinished })` | Manual handoff (prefer session_handoff) |
| Read repo summary | `repo_summary_read({ repo_path })` | Auto-generated directory tree + stack info |

### Codebase Search

| Action | Tool | Notes |
|--------|------|-------|
| Search codebase | `code_search_grep({ repo_path, query, is_regex })` | Text/regex search in source files |
| Find symbols | `code_search_symbols({ repo_path, query })` | Find class/function/method definitions |

### Observability & Control

| Action | Tool | Notes |
|--------|------|-------|
| Check system status | `harness_status({ repo_path })` | Active session, pending tasks, recent instincts |
| Log custom event | `audit_log({ event_type, payload })` | For custom tracking |

### Subagents

| Action | Tool | Notes |
|--------|------|-------|
| Invoke a subagent | `subagent_invoke({ role, prompt, context_files, commands })` | role: Coder/Tester/Reviewer |

**When to use subagents:**
- **2+ independent tasks** — Parallel work on non-overlapping files
- **Code + tests + docs** — Split into separate stages with `depends_on`
- **Complex refactoring** — Delegate one layer per subagent

**When NOT to use subagents:**
- Single file edit (< 50 LoC change)
- Sequential dependency chain (read → analyze → decide next)
- Pure research/question (no file modification)

**Input format:**
```javascript
subagent_invoke({
  role: "Coder",                    // Coder | Tester | Reviewer
  prompt: "Implement X feature...", // Detailed instructions
  context_files: ["src/x.ts"],      // Files subagent can read
  commands: ["npm run build"],      // Shell commands to execute
  wait: true                        // Block until complete (default: false)
})
```

---

## CLI Commands

Run these from the terminal (not inside the agent). All commands support `--help` for details.

| Command | Description |
|---------|-------------|
| `harness status [--repo path] [--format json\|table]` | View active session, pending tasks, recent instincts |
| `harness init [path] [--stack auto\|node\|dotnet\|python\|go\|rust\|php] [--force]` | Initialize harness for a repo |
| `harness verify [--repo path]` | Run verification pipeline manually |
| `harness tasks [--repo path] [--status <status>]` | List all logged tasks and their current statuses |
| `harness skills [--list] [--show <name>] [--stack <filter>]` | Browse and view skill content |
| `harness instincts [--list] [--export]` | List or export all instincts |
| `harness install-mcp --ide <name>` | Install MCP config for your IDE (cursor/vscode/claude-code/kiro/antigravity/opencode) |
| `harness orchestrate <title> [--repo path] [--max-loops n] [--steps build,test]` | Auto-task execution (Ralph Loop Orchestrator) |
| `harness doctor [--check-skills-frontmatter] [--fix]` | Verify system health and dependencies |
| `harness tree [--path .] [--depth 4] [--exclude PATTERN] [--output FILE]` | Generate directory tree |
| `harness summary [--path .] [--force]` | Generate repo summary (code map) |
| `harness reindex [--path .]` | Force reindex of repo |
| `harness export [--repo .] [--output FILE]` | Export harness state to JSON |
| `harness import <file.json>` | Import harness state from JSON |
| `harness workers [--list] [--kill <id>] [--cleanup] [--repo path]` | Manage subagent worker processes |
| `harness hooks [--list] [--validate] [--dry-run --tool <name> --args <json>]` | Inspect and test hook configurations |
| `harness report [--period 7d\|30d\|all] [--repo path] [--format json\|table]` | Generate reliability and latency report |

---

## Workflow

```
session_start → load skills → select task → execute → verify → handoff
```

### Before You Start

1. Run `session_start({ repo_path: "." })` to get context, pending tasks, and suggested skills
2. Read this file and `.harness/repo-summary.md` to understand the codebase
3. Use `skill_suggest({ task_title })` or `skill_list()` to load relevant skills
4. Read `handoff_read({ repo_path: "." })` to pick up from previous session

### During Work

1. **Choose or create a task** — `task_create({ title, scope })` for new work; `task_list()` for pending tasks
2. **Keep instincts in mind** — `instinct_get({ tags })` to recall patterns from past sessions
3. **Check scope before editing** — `scope_check({ repo_path: ".", file_path })` to verify you're allowed
4. **Make changes incrementally**, touching only what the task requires
5. **Log progress** — `progress_log({ repo_path: ".", entry: { summary, status, files_changed } })` after each meaningful change

### Before Finishing

1. **Run verification** — `verify_run({ repo_path: "." })` — all steps must pass
2. **Record outcomes** — `instinct_record_outcomes({ session_id, outcome })` to help harness learn
3. **Create artifacts** (plans, research, reviews) in `.harness/artifacts/` if the work warrants documentation
4. **Call `session_handoff`** with a clear summary, unfinished items, and next steps

---

## Non-Negotiable Rules

1. **Verify before done** — Always run `verify_run` before marking any task complete
2. **Stay in scope** — Check `scope_check` before editing files outside your task's scope
3. **Log progress** — Use `progress_log` after each meaningful change
4. **Handoff at end** — Always call `session_handoff` before ending a session
5. **Record outcomes** — Call `instinct_record_outcomes` to teach harness what worked
6. **No silent failures** — If verification fails, fix it or report it

---

## Quality Rubric — What Good Looks Like

A well-executed session has these characteristics:

| Metric | Good Session | Needs Improvement |
|--------|--------------|-------------------|
| **Handoff** | 1 handoff written with clear summary + next steps | No handoff or handoff empty |
| **Progress logs** | 1+ entries after meaningful changes | No logs or logs only at start/end |
| **Verification** | `verify_run` passes all steps | Verification skipped or failed |
| **Scope** | 0 scope violations (all edits within task scope) | 1+ scope violations |
| **Outcomes** | `instinct_record_outcomes` called with success/failure | Outcomes not recorded |
| **Artifacts** | Plans/reviews created if task warrants documentation | Missing docs for complex work |

**Ideal session flow:**
```
session_start → task_create → [progress_log × N] → verify_run (pass) 
  → session_handoff → instinct_record_outcomes (success)
```

---

## Troubleshooting

### Common Issues

| Issue | Cause | Solution |
|-------|-------|----------|
| **MCP server not responding** | Server crashed or not started | Restart your IDE or run `harness doctor` to verify |
| **`verify_run` fails on lint** | Linting changed files only, but files outside scope | Check `verify.yaml` → set `changed_only: false` for full lint |
| **`skill_load` returns empty** | Skill name typo or doesn't exist | Run `harness skills --list` to see available skills |
| **`scope_check` blocks my edit** | File outside task scope | Review `.harness/scope.yaml` or update task scope |
| **Tests timeout** | Slow tests or network dependency | Check `verify.yaml` → increase `timeout` per step |
| **Session not found error** | Session expired or ID wrong | Run `harness status` to get active session ID |

### Debug Commands

```bash
harness doctor                    # Check system health
harness status --repo .           # Get active session + pending tasks
harness verify --repo .           # Run verification manually
harness skills --list             # List all available skills

# Cross-platform file reading (works on Windows + Unix):
# Windows PowerShell: Get-Content .harness\handoff_last.json
# Unix/Mac: cat .harness/handoff_last.json
# Or use: harness status --repo . (shows handoff info)
```

---

## Project Structure

| Path | Purpose |
|------|---------|
| `AGENTS.md` | This file — agent instructions |
| `AGENTS_OLD.md` | Previous agent instructions (if backed up during init) |
| `.harness/progress.md` | Session history |
| `.harness/feature_list.json` | Feature scope boundaries |
| `.harness/scope.yaml` | Allowed/forbidden paths |
| `.harness/verify.yaml` | Verification pipeline config |
| `.harness/handoff_last.json` | Session context for resumption |
| `.harness/config.yaml` | Repo identity and configuration |
| `.harness/repo-summary.md` | Directory tree map and stack information (read first) |
| `.harness/repo-summary.meta.json` | Repository metadata |
| `.harness/artifacts/` | Plans, research, and review documents |

---

## Skills

Use `skill_list()` to see all available skills. Recommended starting points:

**Core Workflow (always load):**
- `harness-workflow` — The 5-subsystem lifecycle (core)
- `karpathy-guidelines` — Think, Simplicity, Surgical, Goal-Driven
- `strategic-compact` — Context-window optimization strategies

**Development Patterns:**
- `read-first` — Search before writing (critical to avoid redundant work)
- `tdd-workflow` — Test-driven development patterns
- `systematic-diagnosis` — Structured debugging approach
- `subagent-driven-development` — Parallel delegation patterns

**Design & Planning:**
- `design-grilling` — Challenge design decisions early
- `brainstorming` — Multi-option exploration with tradeoff matrix
- `architecture-review` — Evaluate module structure and coupling

**Session Completion:**
- `finishing-a-development-branch` — Proper branch completion workflow
- `deep-learning-review` — Generate learning docs after session/project (elii style)
- `code-review-workflow` — Self-review checklist before merge