<!--
  AGENTS.md.tpl — Template for repo-specific agent instructions
  Template version: 1.3
  Generated by harness-os v{{VERSION}}
  
  This file is processed by `harness init` to create AGENTS.md for new repos.
  Variables: {{REPO_NAME}}, {{VERSION}}, {{DATE}}, {{STACK}}, {{PM_NAME}}, {{PM_INSTALL}}, {{PM_RUN}}
  Conditionals: {{#if_node}}, {{#if_dotnet}}, {{#if_python}}, {{#if_go}}, {{#if_php}}, {{#if_rust}}
-->

# {{REPO_NAME}} — Agent Instructions

{{OLD_AGENTS_NOTE}}

---

## ⚠️ MANDATORY COMPLIANCE WORKFLOW — READ THIS FIRST OR YOUR WORK WILL BE REJECTED

> [!IMPORTANT]
> **AI AGENTS OFTEN SKIP THESE STEPS. THIS IS UNACCEPTABLE.**
> Every development task (new features, bugs, refactoring) MUST follow this workflow.
> The harness-os system tracks all tool executions. If you mark a task as done but skipped `verify_run` or `session_handoff`, the session is flagged as non-compliant and your code changes will be rejected or reverted.

### Decision: Quick, Full, or Doc-only?

| Condition | Path |
|-----------|------|
| Doc-only change | **Doc-only** — no `verify_run` needed |
| Single-file code fix | **Quick** |
| Multi-file, new feature, refactor, bug fix | **Full** |

> **Rule:** If any step in the session edits code, use Full Path for the entire session.

### Doc-only Path
```
session_start(".", { quick: true })  →  edit docs  →  session_handoff(...)
```

### Quick Path
```
session_start(".", { quick: true })  →  fix + verify_run(".")  →  session_handoff(...)
```

### Full Path (11 steps — follow in order)

```text
[ ] 1.  session_start(".", { variant_id: "coding-strict" })
        ← MANDATORY FIRST. Read `suggested_skills` & `workflow_guidance` from response.
[ ] 2.  repo_summary_read(".")          ← understand codebase before coding
[ ] 3.  Read last handoff from session_start response ← avoid repeating previous work
[ ] 4.  task_create("title", { task_type: "feature|bugfix|refactor|..." })
        ← ONE task per session. Read `suggested_skills` from response.
        ← Create plan in `.harness/artifacts/` if task is complex.
[ ] 5.  skill_load(...)
        ← Load `harness-workflow` + ALL suggested skills with score >= 1.5 from steps 1 & 4.
[ ] 6.  scope_check(".", file_path)     ← before editing EACH file
[ ] 7.  Make changes incrementally
        ← Load stack-specific skills if applicable (e.g., `csharp-feature`, `php-codeigniter-4-workflow`)
[ ] 8.  progress_log(".", { summary, status: "in-progress" })
[ ] 9.  verify_run(".")                 ← ALL steps must pass. MANDATORY before handoff.
[ ] 10. skill_load("code-review-workflow") → self-review checklist
[ ] 11. session_handoff(...)            ← MANDATORY LAST ACTION
        ← Also call instinct_record_outcomes(...) to close the learning loop.
        ← If failure patterns detected (repeated failures, low-value instincts, workflow violations):
           call aegis_analyze(repo_path) → review signals → aegis_propose(...) if warranted.
```

### Consequences of skipping steps

| Skipped | Consequence |
|---------|-------------|
| `session_start` | No session ID → `session_handoff` fails → **all progress lost** |
| Suggested skills | Miss TDD/diagnosis skills → **sub-optimal execution, violations flagged** |
| `repo_summary_read` | May edit wrong files or use wrong patterns |
| Last handoff | Repeat work already done by previous agent |
| `scope_check` | Risk editing forbidden paths → **harness flags violation** |
| `progress_log` | Next session loses mid-task context |
| `verify_run` | Task is NOT done → **handoff warning triggered, task rejected** |
| `code-review-workflow` | Risk shipping debug code, bad formatting, missing tests |
| `session_handoff` | All context lost → **next agent starts blind** |

### Non-Dev Tasks (questions, read-only, planning)

Skip all of the above. Just answer directly. Examples: trả lời câu hỏi, review/đọc code, lên plan, viết docs/specs, research.

---

## 📋 MANDATORY SELF-COMPLIANCE CHECKLIST

Append this in your final response before claiming the task is complete:

```markdown
### Agent Compliance Checklist:
- [ ] Ran `session_start` first with correct options?
- [ ] Created task using `task_create` (Full Path)?
- [ ] Loaded suggested skills (score >= 1.5)?
- [ ] Used `scope_check` before modifying any files?
- [ ] Documented progress with `progress_log`?
- [ ] Verification pipeline (`verify_run`) passed successfully?
- [ ] Self-reviewed using `code-review-workflow`?
- [ ] Ended session with `session_handoff` + `instinct_record_outcomes`?
```

---

## Project Overview

This is a **{{STACK}}** project managed by harness-os. The harness ensures agents verify before claiming done, stay within scope, maintain context across sessions, and learn from patterns.

- **Repo:** {{REPO_NAME}}
- **Stack:** {{STACK}}
- **Package Manager:** {{PM_NAME}}
- **Harness version:** {{VERSION}}

---

## Build Commands

{{#if_node}}
```bash
{{PM_INSTALL}}           # Install dependencies
{{PM_RUN}} build         # Build project
{{PM_RUN}} test          # Run tests
{{PM_RUN}} lint          # Lint check
```

> Note: This repo uses **{{PM_NAME}}**. If not available, use npm as fallback.
{{/if_node}}
{{#if_dotnet}}
```bash
dotnet restore              # Install dependencies
dotnet build --no-restore   # Build project
dotnet test --no-build      # Run tests
dotnet format --verify-no-changes  # Lint check
```
{{/if_dotnet}}
{{#if_python}}
```bash
pip install -e .    # Install dependencies
pytest              # Run tests
ruff check .        # Lint check
```
{{/if_python}}
{{#if_go}}
```bash
go mod download     # Install dependencies
go build ./...      # Build project
go test ./...       # Run tests
golangci-lint run   # Lint check
```
{{/if_go}}
{{#if_php}}
```bash
composer install         # Install dependencies
composer dump-autoload   # Regenerate autoloader
vendor/bin/phpunit       # Run tests
vendor/bin/phpcs         # Lint (PSR-12)
```
{{/if_php}}
{{#if_rust}}
```bash
cargo build         # Build project
cargo test          # Run tests
cargo clippy        # Lint check
```
{{/if_rust}}

---

## Rules — Violation = Task Failed

1. **`session_start` before dev tasks** — Start a session before any coding task.
2. **Verify before done** — Always run `verify_run` before marking any task complete.
3. **Stay in scope** — Check `scope_check` before editing files outside your task's scope.
4. **Log progress** — Use `progress_log` after each meaningful change.
5. **Handoff at end** — Always call `session_handoff` before ending a session.
6. **No silent failures** — If verification fails, fix it or report it. Never pretend it passed.
7. **⛔ Commit Gate** — NEVER automatically commit or push code. List modified files, summarize changes, propose a commit message, and wait for explicit confirmation (`OK`).
8. **📝 Encoding** — Use UTF-8 (no BOM). Vietnamese text must be fully accented.

---

## Core MCP Tools

| Domain | Key Tools | Purpose |
|--------|-----------|---------|
| **Session** | `session_start`, `session_handoff` | Lifecycle and context handoffs |
| **Tasks** | `task_create`, `task_list`, `task_update` | Create and track tasks |
| **Verification** | `verify_run` | Run install → build → test → lint |
| **State** | `progress_log`, `handoff_read` | Log progress; read prior context |
| **Scope** | `scope_check`, `scope_get` | Enforce file path restrictions |
| **Search** | `code_search_grep`, `code_search_symbols` | Find code patterns and symbols |
| **Learning** | `instinct_add`, `instinct_get`, `instinct_record_outcomes` | Record and query learned patterns |
| **Aegis** | `aegis_analyze`, `aegis_propose` | Detect failure patterns; propose instinct merges/prunes |
| **Subagents** | `subagent_invoke` | Delegate to parallel worker agents |

### Subagent Usage Example

```javascript
subagent_invoke({
  role: "Coder",                    // Coder | Tester | Reviewer
  prompt: "Implement X feature...", // Detailed instructions
  context_files: ["src/x.ts"],      // Context files
  commands: ["npm run build"],      // Verification commands
  wait: true
})
```

---

## Skills System

Formula: **`[Tier-1 Core] + [Stack Baseline] + [Task-Type] + [Add-ons]`**

| Task | Formula |
|------|---------|
| New C# feature | `harness-workflow` + `csharp-baseline` + `csharp-feature` + `tdd-workflow` |
| Fix bug C# | `harness-workflow` + `csharp-baseline` + `systematic-diagnosis` + `csharp-bugfix` |
| Fix bug PHP CI4 | `harness-workflow` + `php-baseline` + `systematic-diagnosis` + `php-codeigniter-4-workflow` |
| Code review | `harness-workflow` + `code-review-workflow` |
| Feature design | `harness-workflow` + `brainstorming` → `design-grilling` |

**Tiers:**
1. **Tier 1 (always load):** `harness-workflow`, `karpathy-guidelines`, `strategic-compact` + stack baseline
2. **Tier 2 (suggested, load if score >= 1.5):** `tdd-workflow`, `systematic-diagnosis`, `code-review-workflow`, `read-first`, `verification-loop`
3. **Tier 3 (on-demand):** `write-a-skill`

---

## Quality Rubric — What Good Looks Like

| Metric | Good | Needs Improvement |
|--------|------|-------------------|
| Handoff | Written with clear summary + next steps | Empty or missing |
| Progress logs | 1+ entries after meaningful changes | None, or only at start/end |
| Verification | `verify_run` passes all steps | Skipped or failed |
| Scope | 0 violations | 1+ violations |
| Artifacts | Plans/reviews in `~/.harness/repos/{repo_id}/artifacts/` for complex tasks | Missing docs |

**Ideal flow:** `session_start` → `task_create` → [`progress_log` × N] → `verify_run` (pass) → `session_handoff` → `instinct_record_outcomes` → (khi thấy failure patterns) `aegis_analyze` → `aegis_propose`

---

## Troubleshooting

| Problem | Fix |
|---------|-----|
| MCP server not responding | Restart IDE or run `harness doctor` |
| `verify_run` fails on lint | Check `verify.yaml`, set `changed_only: false` |
| `scope_check` blocks edit | Review `.harness/scope.yaml` or update task scope |
| Session not found | Run `harness status` to retrieve active session_id |

### `.harness/` directory structure (repo-local)
- `scope.yaml` — allowed/forbidden paths
- `verify.yaml` — verification config
- `never_again.md` — critical lessons

> State files are stored globally at `~/.harness/repos/{repo_id}/`:
> `progress.md`, `handoff_last.json`, `artifacts/` (plans, research, reviews)
